# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: News
    url: post
    weight: 30
  - name: Projects
    url: projects
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Datasets
    url: datasets
    weight: 60
  - name: Talks
    url: talks
    weight: 65
  - name: Jobs
    url: opportunities
    weight: 70
  - name: Contact
    url: contact
    weight: 80

